# start AeroSpace at login
start-at-login = true

after-startup-command = ['exec-and-forget sketchybar']

# notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

# some basic window configs
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

[key-mapping]
    preset = 'qwerty'

[gaps]
	inner.horizontal = 10
	inner.vertical =   10
	outer.left =       10
	outer.bottom =     10
	outer.top =        10
	outer.right =      10

[mode.main.binding]
	alt-enter = 'exec-and-forget /Applications/kitty.app/Contents/MacOS/kitty --single-instance -d ~'
	alt-q = 'close --quit-if-last-window'
